# Generated by Django 4.1.3 on 2022-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jar',
            name='type',
        ),
        migrations.AddField(
            model_name='jar',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jar',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
