# Generated by Django 4.1.3 on 2022-11-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_jar_type_jar_quantity_alter_jar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(choices=[('W', 'Windex'), ('I', 'Invisible Glass'), ('G', 'Glass Plus')], default='W', max_length=1)),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jar')),
            ],
        ),
    ]
