# Generated by Django 4.1.3 on 2022-11-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(verbose_name='Cleaning date'),
        ),
    ]
